# Generated by Django 4.2.30 on 2026-06-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.SlugField(help_text='Unique slug, e.g. francisco2001', max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField()),
                ('study_type', models.CharField(choices=[('Journal Article', 'Journal Article'), ('Technical Report', 'Technical Report'), ('Thesis', 'Thesis'), ('Other', 'Other')], default='Journal Article', max_length=50)),
                ('status', models.CharField(choices=[('Legacy Study (Pre-Guidelines)', 'Legacy Study (Pre-Guidelines)'), ('MVNP-PAMB Approved Publication', 'MVNP-PAMB Approved Publication')], default='Legacy Study (Pre-Guidelines)', max_length=80)),
                ('featured', models.BooleanField(default=False)),
                ('abstract', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='repository/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='mvnp_repo.category')),
            ],
            options={
                'verbose_name_plural': 'Studies',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='mvnp_repo.study')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
