# Generated by Django 4.2.30 on 2026-06-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvnp_repo', '0005_seed_research_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='study',
            name='study_type',
            field=models.CharField(choices=[('Journal Article', 'Journal Article'), ('Technical Report', 'Technical Report'), ('Undergraduate Thesis', 'Undergraduate Thesis'), ('Graduate Thesis', 'Graduate Thesis'), ('Post-Graduate Thesis', 'Post-Graduate Thesis'), ('Other', 'Other')], default='Journal Article', max_length=50),
        ),
    ]
